services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: campusshare-web
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: always
